# Generated by Django 2.0.13 on 2019-06-04 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eggify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eggnt',
            name='user_num',
        ),
    ]
