# Generated by Django 2.0.13 on 2019-06-04 22:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eggify', '0002_remove_eggnt_user_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eggnt',
            name='num',
        ),
        migrations.AddField(
            model_name='eggnt',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
