# Generated by Django 2.0.13 on 2019-06-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggify', '0003_auto_20190604_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggnt',
            name='words',
            field=models.CharField(editable=False, max_length=5000),
        ),
    ]
