# Generated by Django 2.0.13 on 2019-06-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggify', '0006_auto_20190604_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggnt',
            name='uid',
            field=models.IntegerField(default=278386999747255395689162397743859323681, editable=False),
        ),
    ]
