# Generated by Django 2.0.13 on 2019-06-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggify', '0007_auto_20190604_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggnt',
            name='uid',
            field=models.IntegerField(default=144515383183420510853275499481612218951, editable=False),
        ),
    ]
