# Generated by Django 2.0.13 on 2019-06-04 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggify', '0008_auto_20190604_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggnt',
            name='uid',
            field=models.CharField(default='f4523017-c594-4214-ba44-57cecec66490', editable=False, max_length=50),
        ),
    ]
