# Generated by Django 2.0.13 on 2019-06-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggify', '0009_auto_20190604_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggnt',
            name='uid',
            field=models.CharField(default='60a07f4a-6d5c-4cfb-8b28-e4263c950b71', editable=False, max_length=50),
        ),
    ]
