# Generated by Django 2.0.13 on 2019-06-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggify', '0010_auto_20190604_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggnt',
            name='uid',
            field=models.CharField(default='0ab7f578-c672-4c7b-b1cf-7357e9c0495d', editable=False, max_length=50),
        ),
    ]
