# Generated by Django 2.2.2 on 2019-06-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggify', '0011_auto_20190604_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggnt',
            name='uid',
            field=models.CharField(default='6d409d52-6f74-494a-a000-dd4cf8ab283b', editable=False, max_length=50),
        ),
    ]
