# Generated by Django 2.2.2 on 2019-06-05 02:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eggify', '0012_auto_20190605_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggnt',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 5, 2, 29, 14, 627078, tzinfo=utc), editable=False, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='eggnt',
            name='uid',
            field=models.CharField(default='6f96548e-33cb-4855-a469-c945c07a5a93', editable=False, max_length=50),
        ),
    ]
