# Generated by Django 2.2.2 on 2019-06-05 02:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggify', '0014_auto_20190605_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggnt',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.utcnow, editable=False, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='eggnt',
            name='uid',
            field=models.CharField(default='eace19d9-4f27-4686-b357-5a1040a57ad1', editable=False, max_length=50),
        ),
    ]
