# Generated by Django 2.2.2 on 2019-06-05 19:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eggify', '0017_auto_20190605_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eggnt',
            name='uid',
        ),
        migrations.AlterField(
            model_name='eggnt',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 5, 19, 49, 54, 193712, tzinfo=utc), editable=False, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='eggnt',
            name='id',
            field=models.CharField(default='5c38187c-16fa-45e1-9c0d-3c8a4bed1774', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
