# Generated by Django 2.2.2 on 2019-06-06 06:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eggify', '0018_auto_20190605_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggnt',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 6, 6, 48, 22, 134648, tzinfo=utc), editable=False, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='eggnt',
            name='id',
            field=models.CharField(default='14d3ad1b-cbec-46cf-bd5a-fb2b70f3b347', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
