# Generated by Django 2.2.2 on 2019-06-06 20:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eggify', '0020_auto_20190606_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eggnt',
            name='created_at',
        ),
        migrations.AddField(
            model_name='eggnt',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 6, 20, 9, 27, 716025, tzinfo=utc), verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='eggnt',
            name='id',
            field=models.CharField(default='b8051f41-1f97-430b-9c91-5508806c1c94', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eggnt',
            name='words',
            field=models.CharField(max_length=5000),
        ),
    ]
