# Generated by Django 2.2.2 on 2019-06-06 20:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eggify', '0023_auto_20190606_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggnt',
            name='id',
            field=models.CharField(default='65c713aa-8b95-41c6-b47a-b747df3ef268', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eggnt',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 6, 20, 17, 57, 463332, tzinfo=utc), verbose_name='updated at'),
        ),
    ]
