# Generated by Django 2.2.2 on 2019-06-06 21:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eggify', '0024_auto_20190606_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggnt',
            name='id',
            field=models.CharField(default='8504f8ba-96cb-447f-a116-8c20ee77c672', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eggnt',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 6, 21, 15, 8, 165611, tzinfo=utc), verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='eggnt',
            name='words',
            field=models.CharField(help_text='Enter text to be eggified!', max_length=5000),
        ),
    ]
