# Generated by Django 2.2.2 on 2019-06-06 23:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eggify', '0026_auto_20190606_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggnt',
            name='id',
            field=models.CharField(default='7d3d6b90-5bc2-4cb7-bd5f-9d4640a7b2e9', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eggnt',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 6, 23, 53, 51, 475985, tzinfo=utc), verbose_name='updated at'),
        ),
    ]
