# Generated by Django 2.2.2 on 2019-06-07 02:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eggify', '0027_auto_20190606_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggnt',
            name='id',
            field=models.CharField(default='6b7bf253-fb9b-44a7-96a8-94301dd653aa', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eggnt',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 7, 2, 16, 33, 968285, tzinfo=utc), verbose_name='updated at'),
        ),
    ]
