# Generated by Django 2.2.2 on 2019-06-07 02:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eggify', '0031_auto_20190607_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggnt',
            name='id',
            field=models.CharField(default='69246238-613d-4c82-a0b1-9d04e214b672', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eggnt',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 7, 2, 35, 12, 679760, tzinfo=utc), verbose_name='updated at'),
        ),
    ]
