# Generated by Django 2.2.2 on 2019-06-07 02:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eggify', '0032_auto_20190607_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggnt',
            name='id',
            field=models.CharField(default='6f99356e-ab6b-41b5-920e-d7ab3a6f5afe', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eggnt',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 7, 2, 38, 39, 706751, tzinfo=utc), verbose_name='updated at'),
        ),
    ]
