# Generated by Django 2.2.2 on 2019-06-07 02:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eggify', '0033_auto_20190607_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggnt',
            name='id',
            field=models.CharField(default='b3b387af-0659-4692-b139-faa011e990a7', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eggnt',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 7, 2, 41, 35, 840071, tzinfo=utc), verbose_name='updated at'),
        ),
    ]
