# Generated by Django 2.2.2 on 2019-06-07 05:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eggify', '0035_auto_20190607_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggnt',
            name='id',
            field=models.CharField(default='d2eac2dd-4fca-47f2-b5db-22693232c949', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eggnt',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 7, 5, 17, 12, 493127, tzinfo=utc), verbose_name='updated at'),
        ),
    ]
