# Generated by Django 2.2.2 on 2019-06-07 19:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eggify', '0035_auto_20190607_0246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eggnt',
            options={'ordering': ('updated_at',)},
        ),
        migrations.AlterField(
            model_name='eggnt',
            name='id',
            field=models.CharField(default='d1a90d30-e87c-4405-894c-d8b2ded982d1', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eggnt',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 7, 19, 39, 16, 530248, tzinfo=utc), editable=False, verbose_name='updated at'),
        ),
    ]
