# Generated by Django 2.2.2 on 2019-06-07 19:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eggify', '0036_auto_20190607_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eggnt',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterField(
            model_name='eggnt',
            name='id',
            field=models.CharField(default='74e45ba7-06ec-48f9-aa3e-d64668b4f0ce', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eggnt',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 7, 19, 50, 38, 194242, tzinfo=utc), editable=False, verbose_name='updated at'),
        ),
    ]
