# Generated by Django 2.2.2 on 2019-06-07 20:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eggify', '0037_auto_20190607_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggnt',
            name='id',
            field=models.CharField(default='9ff95e7e-93da-48d0-8b4a-9deec922856e', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eggnt',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 7, 20, 7, 49, 997896, tzinfo=utc), editable=False, verbose_name='updated at'),
        ),
    ]
