# Generated by Django 2.2.2 on 2019-06-08 00:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eggify', '0038_auto_20190607_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggnt',
            name='id',
            field=models.CharField(default='9ede71d5-bfd3-4aa0-bda4-b3c37082326a', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eggnt',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 8, 0, 36, 55, 47438, tzinfo=utc), editable=False, verbose_name='updated at'),
        ),
    ]
