# Generated by Django 2.2.2 on 2019-06-08 01:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eggify', '0039_auto_20190608_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggnt',
            name='id',
            field=models.CharField(default='37d70e32-2e63-48f4-bfbc-42134cfd6cf1', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eggnt',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 8, 1, 44, 42, 520291, tzinfo=utc), editable=False, verbose_name='updated at'),
        ),
    ]
