# Generated by Django 2.2.2 on 2019-06-08 01:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eggify', '0040_auto_20190608_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggnt',
            name='id',
            field=models.CharField(default='1fe41f33-1874-4555-aba4-9d68e9ed3513', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eggnt',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 8, 1, 46, 35, 743217, tzinfo=utc), editable=False, verbose_name='updated at'),
        ),
    ]
