# Generated by Django 2.2.2 on 2019-06-08 02:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eggify', '0042_auto_20190608_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggnt',
            name='id',
            field=models.CharField(default='5ddede43-d0d2-4f7e-875d-76bc5bf8553b', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eggnt',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 8, 2, 42, 45, 984102, tzinfo=utc), editable=False, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='eggnt',
            name='words',
            field=models.TextField(editable=False, help_text='Enter text to be eggified!'),
        ),
    ]
