# Generated by Django 2.2.2 on 2019-06-08 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eggify', '0036_auto_20190607_0517'),
        ('eggify', '0043_auto_20190608_0242'),
    ]

    operations = [
    ]
