# Generated by Django 2.2.2 on 2019-06-08 06:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eggify', '0045_auto_20190608_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggnt',
            name='id',
            field=models.CharField(default='c12d139d-b105-4f53-acfe-4ee316da901b', editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eggnt',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 8, 6, 38, 6, 367445, tzinfo=utc), editable=False, verbose_name='updated at'),
        ),
    ]
