# Generated by Django 2.2.2 on 2019-06-08 06:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eggify', '0046_auto_20190608_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggnt',
            name='id',
            field=models.CharField(default='ce7c0cc7-55e8-4f50-be4d-21c8606ef170', editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eggnt',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 8, 6, 42, 15, 931120, tzinfo=utc), editable=False, verbose_name='updated at'),
        ),
    ]
