# Generated by Django 2.2.2 on 2019-06-08 20:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eggify', '0050_auto_20190608_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggnt',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 8, 20, 27, 29, 424559, tzinfo=utc), editable=False, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='eggnt',
            name='id',
            field=models.CharField(default='13f9f6fd-fd39-4cba-8d80-bcaa784aaab5', editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
