# Generated by Django 2.2.2 on 2019-06-18 04:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eggify', '0052_auto_20190618_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggnt',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 18, 4, 59, 6, 948870, tzinfo=utc), editable=False, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='eggnt',
            name='id',
            field=models.CharField(default='ff9b97e1-4e19-4992-995c-e26484c62d55', editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
